### ISSUE TITLE
Cannot reproduce paths.txt with current HEAD

### ISSUE THREAD

**Issue by jarsi** [kmsabrin/hourglass-celegans#1]
Hi,
I enjoyed reading the paper on the hourglass structure of the c elegans a lot and thought I'd dig into the code. I tried to reproduce the paths.txt file via running
```
javac HourglassAnalysis.java
java HourglassAnalysis edge_list source_list target_list +2
```
but I get 
> a d g j
> b e i l
> c e i l
> c i l

instead of the table that is shown in the README.md. Reverting the newest commit solves this issue.

**Comment by kmsabrin** [comment]
Hi,
Thanks for catching this. I was trying some optimization but didn't finish/test it properly. I will revert for now and hopefully try again in some later time.
Cheers.
